Rails.application.routes.draw do
  # Authentication routes (generated by the authentication generator)
  resource :session, only: [ :new, :create, :destroy ]
  resources :passwords, param: :token
  resources :registrations, only: [ :new, :create ]

  # Main application routes
  root 'dashboard#index', as: :dashboard_index

  resources :tasks do
    member do
      patch :toggle_status
    end
  end

  resources :projects do
    resources :tasks, only: [:index, :new, :create ]
  end

  # Dashboard stats update route
  get 'dashboard/projects_stats', to: 'dashboard#projects_stats'

  # Admin routes for exploring features
  namespace :admin do
    get :index
    get :users
    get :tasks
    get :cache_stats
    # New route for Turbo Frame refresh
    get :refresh_cache_stats
    delete :clear_cache
    delete :clear_project_cache
  end

  # API routes for AJAX requests
  namespace :api do
    namespace :v1 do
      resources :tasks, only: [ :index, :update ]
    end
  end

  # Health check
  get "up" => "rails/health#show", as: :rails_health_check

  # Mount action Cable server
  mount ActionCable.server => "/cable"

end