Rails.application.routes.draw do
  # Authentication routes (generated by the authentication generator)
  resources :sessions, only: [:new, :create, :destroy]
  resources :passwords, param: :token
  resources :registrations, only: [:new, :create]

  # Main application routes
  root 'dashboard#index'

  resources :tasks do
    member do
      patch :toggle_status
    end
  end

  resources :projects do
    resources :tasks, only: [:new, :create]
  end

  # Admin routes for exploring features
  namespace :admin do
    get :index
    get :users
    get :tasks
    get :cache_stats
    delete :clear_cache
  end

  # API routes for AJAX requests
  namespace :api do
    namespace :v1 do
      resources :tasks, only: [:index, :update]
    end
  end

  # Health check
  get "up" => "rails/health#show", as: :rails_health_check
end